### ISSUE TITLE
Impossible to access an attribute

### ISSUE THREAD

**Issue by mikestecker** [dukt/videos#1]
I'm getting a `Impossible to access an attribute ("title") on a string variable ("http://youtu.be/zB4I68XVPzQ").` error when trying to output the video using the variables.

It doesn't seem like it's using the variable properly?

here's what isn't working:
```
{% set videoBlock = entry.videoFeatureBlock.one() %}
{% set vid = videoBlock.video %}
{{ vid.title }}
```

Below works however, but I was thinking it would be simpler?
```
{% set videoBlock = entry.videoFeatureBlock.one() %}
{% set vid = craft.videos.getVideoByUrl(videoBlock.video) %}
{{ vid.title }}
```

**Comment by benjamindavid** [comment]
Missed that during the transition to Craft 3, should be fixed now. Thanks for the heads up!
