### ISSUE TITLE
Accessing, in templates, an object of all videos

### ISSUE THREAD

**Issue by olets** [dukt/videos#13]
A project I'm working on needs a video gallery of all the videos on a particular Vimeo channel. I'm also planning on using the Video plugin on this project. Rather than manually retrieving a list of the videos myself, I wonder if there's a way to use the data the Video plugin is configured to retrieve. Assuming this doesn't already exist as an undocumented feature, it'd be amazing to add an enhancement that would support using something like {{ craft.video.videos }} to return an object with all the videos' data. Thoughts?

**Comment by benjamindavid** [comment]
Hey @olets, it is on our list of things to explore for future versions. I've just added an issue for it so you can keep track of the implementation of that feature: https://github.com/dukt/videos/issues/13

**Comment by olets** [comment]
Cool! I'll watch #15 ;) And thanks for all the great plugins
