### ISSUE TITLE
Cannot have videos and social installed together

### ISSUE THREAD

**Issue by 1stevengrant** [dukt/videos#16]
I'm trying to upgrade a Craft 2 site right now and running into an issue installing Videos and Social together.

In our upgrade I installed Social first and that was fine but then couldn't get Videos installed.

I then tried a clean Craft 3 instance installing Videos first but then couldn't get Social installed.

Composer message was

Problem 1
    - Installation request for dukt/social ^2.0 -> satisfiable by dukt/social[2.0.0].
    - Conclusion: remove league/oauth2-google 2.2.0
    - Conclusion: don't install league/oauth2-google 2.2.0
    - dukt/social 2.0.0 requires league/oauth2-google ^3.0 -> satisfiable by league/oauth2-google[3.0.0, 3.0.1].
    - Can only install one of: league/oauth2-google[3.0.0, 2.2.0].
    - Can only install one of: league/oauth2-google[3.0.1, 2.2.0].
    - Installation request for league/oauth2-google (locked at 2.2.0) -> satisfiable by league/oauth2-google[2.2.0].

Any ideas to resolve this?

**Comment by bstein-clever** [comment]
Also experiencing this right now.

I think the right solution is to just make a new release, they already upgraded the requirement, here: https://github.com/dukt/videos/commit/1976fd62412c92148c9b8ae671dcbb93e2232554, they just did the release first.

**Comment by benjamindavid** [comment]
Sorry about that guys, should be fixed now with [2.0.6](https://github.com/dukt/videos/blob/master/CHANGELOG.md#206---2019-03-29).
