### ISSUE TITLE
Private Video Thumbnail Issue

### ISSUE THREAD

**Issue by e-roc** [dukt/videos#17]
### Description
Private Youtube video thumbnails are not loading. I've pinpointed the issue to be a problem with query string after the filename. In /vendor/dukt/videos/src/helpers/VideosHelper.php line #106, add parse_url before passing the path:

`->saveAs(parse_url($path, PHP_URL_PATH));`

### Steps to reproduce

1. In Craft admin, open a video field, and choose a private YouTube video
2. The thumbnail does not load

### Additional info

- Plugin version: 
- Craft version: 3.1.9
- PHP version: 7.1.25
- Plugins & versions: 2.0.5

**Comment by benjamindavid** [comment]
Good catch, thanks!
