### ISSUE TITLE
Implement oauthProviderOptions settings as Environmental Settings

### ISSUE THREAD

**Issue by bro-strummer** [dukt/videos#18]
### Description

Currently, projects utilizing Project Config will plainly store the values of `oauthProviderOptions->vimeo->clientId` and other sensitive settings in `project.yaml`.

To prevent the possibility of exposing these sensitive values in version control, this issue requests that sensitive settings be implemented as [Environmental Settings](https://docs.craftcms.com/v3/extend/environmental-settings.html).

#### Current config file (exposes values to `project.yaml`)
```php
<?php

return [
    'oauthProviderOptions' => [
        'vimeo' => [
            'clientId' => getenv('VIMEO_CLIENT_ID'),
            'clientSecret' => getenv('VIMEO_CLIENT_SECRET'),
        ]
    ]
];
```

#### Ideal config file (references env var without exposing it to `project`)
```php
<?php

return [
    'oauthProviderOptions' => [
        'vimeo' => [
            'clientId' => '$VIMEO_CLIENT_ID',
            'clientSecret' => '$VIMEO_CLIENT_SECRET',
        ]
    ]
];
```

**Comment by benjamindavid** [comment]
Should be working now, thanks @bro-strummer!

**Comment by bro-strummer** [comment]
Thanks @benjamindavid!
