### ISSUE TITLE
Unknown Method

### ISSUE THREAD

**Issue by mikestecker** [dukt/videos#2]
I'm getting  a `Calling unknown method: dukt\videos\fields\Video::prepValue()` when going to edit an entry that already existed before I added the new videos field to the section. Let me know if you need more from my logs.

**Comment by mikestecker** [comment]
I saw your note on fixing #1 and manually changed line 45 of `src/fields/Video.php` to `$value = $this->normalizeValue($value);` and it works.

**Comment by benjamindavid** [comment]
Should be good now, thanks!
