### ISSUE TITLE
YouTube Access Token Expiry in project.yaml

### ISSUE THREAD

**Issue by aarmitage** [dukt/videos#21]
### Description
We're working across locations using project.yaml to sync our respective field changes across locally hosted copies of a site. We've also disabled admin access on our staging (centralised) copy of the site to avoid anyone accidentally editing fields or structures here.

Having added the Video plugin and made the connections to both Vimeo and YouTube, the YouTube connection generates a token that expires after 1 hour.

On the staging server with admin changes disabled, there is no way for the token to be refreshed in the project.yaml file as it's read only, therefore the connection breaks and the video browser fails to load.

The Vimeo connection doesn't appear to have an expiry set, with `null` appearing in the project.yaml file.

### Steps to reproduce

1. Connect to YouTube and Vimeo services locally
2. Push project.yaml file to staging environment with admin changes disabled
3. Wait 1 hour
4. Attempt to browse videos from a video field to see the error below.

<img width="990" alt="Screenshot 2019-05-15 at 15 21 45" src="https://user-images.githubusercontent.com/1152884/57783176-9a6f6e00-7725-11e9-8823-8da9f3305240.png">

### Additional info

- Plugin version: 2.0.6
- Craft version: 3.1.25
- PHP version: 7.3.5
- Database driver & version: MySQL 5.7.26
- Plugins & versions: n/a

**Comment by ademers** [comment]
I'm having the same issue. I posted a comment in https://github.com/dukt/videos/issues/14 a couple of months ago.

**Comment by aarmitage** [comment]
Ah - missed this being raised in #14. This has been open for a while then, is there an eta on a fix for this please?

**Comment by benjamindavid** [comment]
Should be fixed now, thanks for your patience!

**Comment by aarmitage** [comment]
Amazing Ben, thank you :-)

**Comment by ademers** [comment]
@benjamindavid Thanks!
