### ISSUE TITLE
Database Exception SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by ademers** [dukt/videos#22]
### Description

When updating from 2.0.7 to 2.0.8 and then trying to access `admin/videos/settings`, I get the following error:
```
Database Exception SQLSTATE[42S02]: Base table or view not found: 1146 Table 'example.test.craft_videos_tokens' doesn't exist
The SQL being executed was: SELECT *
FROM `craft_videos_tokens`
WHERE `gateway`='vimeo'
```

### Steps to reproduce

1. Update from 2.0.7 to 2.0.8
2. Visit the plugin's settings page in CP

### Additional info

- Plugin version: 2.0.8
- Craft version: Craft Pro 3.1.28
- PHP version: 7.0.33
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by benjamindavid** [comment]
Sorry, I forgot to update the `schemaVersion` so it didn’t trigger the tokens migration. Videos [2.0.9](https://github.com/dukt/videos/blob/master/CHANGELOG.md#209---2019-06-03) should do it 👍

**Comment by ademers** [comment]
In local dev, where I already had 2.0.8 installed the migration ran OK. However, on Staging, where I still had 2.0.7, I get following error:
```
Executing command: ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.19)
    > create table {{%videos_tokens}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_videos_tokens' already exists
The SQL being executed was: CREATE TABLE `craft_videos_tokens` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`gateway` varchar(255) NOT NULL,
	`accessToken` text,
	`dateCreated` datetime(0) NOT NULL,
	`dateUpdated` datetime(0) NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
```

**Comment by ademers** [comment]
I was able to work around the above as follows:

- Set allowAdminChanges from false to true
- Rename existing `craft_videos_tokens` table
-Run `./craft migrate/all`

**Comment by ademers** [comment]
@benjamindavid Indeed. I originally had `allowAdminChanges` set to 'false` in Staging env. where error was occurring.  I figured it based on info in Buddy error logs.
