### ISSUE TITLE
Migration Error Updating to 2.0.9

### ISSUE THREAD

**Issue by lukebailey** [dukt/videos#23]
### Description
When trying to upgrade from 2.0.8 to 2.0.9 in a production site we are seeing the following read only error when `allowadminchanges` is set to `false` (via `config/general.php`). This is despite the correct project.config file being updated and pushed to source control in our development environment and deployed as part of the code base (so no changes should be required)

![Video Migration Fail](https://user-images.githubusercontent.com/3185073/58891220-09683300-86e4-11e9-83c0-dfb51bf31c10.png)

Subsequent attempts to apply the update then state that the migration failed because the new table craft_videos_tokens already exists (this isn't really an issue if the first attempt succeeded) 

![DB already exisits](https://user-images.githubusercontent.com/3185073/58891233-0d945080-86e4-11e9-81b7-9b2dbdf68cf4.png)

### Steps to reproduce

1. Commit updated `composer.json` and `project.config` files to source control
2. Ensure that set `'allowAdminChanges' => false,` for production mode
2. Deploy codebase to upgrade 2.0.8 to 2.0.9 (tried both via composer or the UI)
3. First failure states that changes to the project config are not possible in read only mode
4. Second failure states that the craft_videos_tokens table already exists (not the cause or an issue but adding anyway)

### Additional info

- Plugin version: 2.0.9
- Craft version: 3.1.28
- PHP version: 7.1.28
- Database driver & version: MySQL 5.7.12

**Comment by lukebailey** [comment]
The migration file appears to try and change the dateModified field which is the cause of failure.

**Comment by benjamindavid** [comment]
Videos [2.0.10](https://github.com/dukt/videos/blob/master/CHANGELOG.md#2010---2019-06-05) should fix this migration issue, feel free to reopen this issue if needed.

Related to https://github.com/dukt/videos/issues/22.

**Comment by lukebailey** [comment]
Works great thanks for the quick fix
