### ISSUE TITLE
Does this plugin work with Vimeo Pro?

### ISSUE THREAD

**Issue by gertst** [dukt/videos#26]
### Description

Can we use this plugin to work with Vimeo Pro videos that are set to "hidden"?
Mind that the vimeo API will not find the video without first logging in... Is this foreseen?

Thanks
www.but.be

**Comment by benjamindavid** [comment]
Yeah, you need to be authenticated on the video platforms that you are willing to use. It should work with Vimeo Pro and hidden videos. Feel free to try it out before buying to make sure it fits your needs.
