### ISSUE TITLE
Not able to see all Youtube playlists

### ISSUE THREAD

**Issue by WHITE-developer** [dukt/videos#28]
### Description
I only see the 5 newest playlists listed in the video field modal, but we have more of them. Is there some configuration that I need to override or something?

### Additional info

- Plugin version: 2.0.10
- Craft version: 3.3.17

**Comment by WHITE-developer** [comment]
@benjamindavid ?

**Comment by WHITE-developer** [comment]
@benjamindavid bump ;)

**Comment by benjamindavid** [comment]
Should be fixed in [Videos 2.0.11](https://github.com/dukt/videos/releases/tag/2.0.11). Thanks for the feedback!
