### ISSUE TITLE
Beta 27 Breaking Change - removed resources

### ISSUE THREAD

**Issue by mikestecker** [dukt/videos#3]
See breaking change: https://github.com/craftcms/cms/blob/master/CHANGELOG-v3.md#removed

The plugin breaks after updating to beta 27 due to the removal of `resources` service `craft\services\Resources` which doesn't even allow the admin to load.

As a temporary solution on my end, I simply commented out lines 70-78 of `src/Plugin.php`

**Comment by benjamindavid** [comment]
Fixed by https://github.com/dukt/videos/commit/bfb9ef3f6bc4a34c8523e6c57f2132ede341c9c9

Thanks again for reporting the issue @mikestecker!
