### ISSUE TITLE
YouTube videos can play simultaneously on one page

### ISSUE THREAD

**Issue by jaytavares** [dukt/videos#35]
### Description

If you add multiple YouTube videos to a single page, the user can play them simultaneously. This violates the YouTube API license agreement. I discovered this because my site was just audited by Google and this was one of the violations.

**Comment by benjamindavid** [comment]
My understanding of the [YouTube license agreement](https://developers.google.com/youtube/terms/required-minimum-functionality) is that you can't _autoplay_ them simultaneously.

> A page or screen must not have more than one YouTube player that automatically plays content simultaneously.

The Videos plugin complies with this rule since you can only play one video at a time in the control panel.

**Comment by jaytavares** [comment]
I'm going to try to push back, citing that. Our site does NOT auto play anything, but we still failed our audit for simply allowing users to play two videos at one time via the Videos plugin. Here's an excerpt of the audit (notice there's no mention of videos playing automatically):

![image](https://user-images.githubusercontent.com/711127/93607757-bdec9d80-f997-11ea-8805-0c47eecfeaa3.jpeg)
