### ISSUE TITLE
Saving image in "" format is not supported

### ISSUE THREAD

**Issue by andrewfairlie** [dukt/videos#40]
### Description
When adding some Vimeo videos to the CMS we get internal server errors of...

```
Saving image in "" format is not supported, please use one of the following extensions: "bmp", "gif", "jpeg", "png", "wbmp", "webp", "xbm"
```

When editing an entry with the broken Video saved, or...

```
{
    "error": "An exception has been thrown during the rendering of a template (\"Saving image in \"\" format is not supported, please use one of the following extensions: \"bmp\", \"gif\", \"jpeg\", \"png\", \"wbmp\", \"webp\", \"xbm\"\")."
}
```

AJAX error when adding the video itself.

- This video is on the authenticated account
- It has full permission and is publicly available 
- Re-uploading the same video then works

### Steps to reproduce

1. This video has the problem https://vimeo.com/431533545 

### Additional info

- Plugin version: 2.0.10
- Craft version: 3.4.24
- PHP version: 7.4.4
- Database driver & version: MySQL 5.7.30

**Comment by benjamindavid** [comment]
I'm not able to replicate with the video you provided, it's generating the thumbnail fine. Could you please replicate the issue and send us your Craft logs at support@dukt.net. Thanks!

**Comment by WHITE-developer** [comment]
Also got that message. In our case the video was removed.
