### ISSUE TITLE
Missing Images causes internal server error on CP

### ISSUE THREAD

**Issue by luke-nehemedia** [dukt/videos#49]
### Description
Today a client contacted me about this error message:

> yii\base\ErrorException: finfo_file(/home/web1/files/craft3/storage/runtime/videos/thumbnails/vimeo/506060813/original/1047228878_1280.jpg): failed to open stream: No such file or directory in /home/web1/files/craft3/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:167
> Stack trace:
> 
I cleared the cache, expecting the plugin to regenerate the previews. But this did not happen. In contrast: Now every page containing a video is not editable anymore and presents with an Internal Server Error. 

This makes a large portion of the site unusable for the client which is very annoying. 

Could you please fix this ASAP or provide me with some information how to solve this issue?

### Additional info
- Plugin version: 2.0.12
- Craft version: 3.6.2
- PHP version: 7.3.26
- Database driver & version: MySQL 5.7.22
- php error log is empty

**Comment by lukebailey** [comment]
We are seeing the same issue (luckily cuaght this before going live), only presenting itself after updating from Craft 3.5 to Craft 3.6

**Comment by andrewhawkes** [comment]
Getting this issue with the plugin version 2.0.12 on Craft 3.6.3

**Comment by lukebailey** [comment]
Have also reached out to support@dukt.net for a response

**Comment by luke-nehemedia** [comment]
Me also, already yesterday, but I have not yet heard back from them.

**Comment by lukebailey** [comment]
@benjamindavid is this something you can look at? It is blocking us from upgrading to Craft 3.6 and I believe affecting others in production

**Comment by luke-nehemedia** [comment]
Any news? It is quite annoying for my clients and is blocking me from updating other ones.

**Comment by lukebailey** [comment]
I've raised a ticket in the main Craft repo to see if they can be more defensive in Craft core against the missing file, would still appreciate a response from the developers at Dukt though as this is a paid plugin

**Comment by lukebailey** [comment]
I have found the fix and confrimed this works locally, would create a PR but the repo appears to be locked down. 

@benjamindavid (or anyone with permissions) could you please change the following so that the plugin is [compatible with Guzzle 7](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md) (`save_to` has been replaced by `sink`)

[Line 119 in the Video Helper](https://github.com/dukt/videos/blob/master/src/helpers/VideosHelper.php#L119) should now read as follows:

```
$response = $client->request('GET', $url, [
    'sink' => $originalPath,
]);
```

**Comment by luke-nehemedia** [comment]
Wow! Thank you soo much! This helps a lot!

I hope they will soon publish the fix. Nevertheless, I find it quite disappointing for a plugin with such a price tag to take so long to even respond into such an issue.

**Comment by mmikkel** [comment]
A possible workaround is to explicitly add a dependency on Guzzle 6 in your project's `composer.json` file before upgrading to Craft 3.6, i.e.

```
composer require guzzlehttp/guzzle:^6.5.1
```

AFAIK Craft 3.6 is still compatible with Guzzle 6; adding an explicit dependency would simply prevent pulling in Guzzle 7 when upgrading to 3.6.x, and keep the Videos plugin afloat until Dukt can fix the issue. Note that Craft's PHP 8 support is off the table without Guzzle 7 though.

**Comment by lukebailey** [comment]
thanks @mmikkel good suggestion.

I think that would be a last resort if the plugin is not updated soon as I would prefer to move across to Guzzle 7, hopefully they can address this soon especially how simple the fix is

**Comment by benjamindavid** [comment]
Sorry for the delay and thanks a lot for looking into this. The plugin has been update to work with Guzzle 7.
