### ISSUE TITLE
Server Error: Saving image in "" format is not supported

### ISSUE THREAD

**Issue by lukebailey** [dukt/videos#54]
### Description

Since upgrading to Craft 3.6.13 we are seeing an internal server error on some entries in the control panel. Scrolling through the stack trace it appears to be because of the video helper function in this plugin

![image](https://user-images.githubusercontent.com/3185073/117845186-39c58e00-b278-11eb-96f8-5e9ff133a20a.png)

![image](https://user-images.githubusercontent.com/3185073/117845847-d0924a80-b278-11eb-88c2-1425c8614669.png)

### Steps to reproduce

1. Upgrade to Craft 3.6.13
2. Visit an entry that uses the Video field

### Additional info

- Plugin version: latest
- Craft version: 3.6.13
- PHP version: 8.0.3

**Comment by lukebailey** [comment]
All our videos are hosted on Vimeo but without public Vimeo URLs, these are configured to only show on listed domains. Here is an example: https://www.winton.com/talks-at-winton/yuval-noah-harari

**Comment by benjamindavid** [comment]
I'm sorry @lukebailey but I'm still unable to replicate this on my end. Could you please replicate the issue and zip send me your Craft logs at contact@dukt.net? Thanks!

**Comment by lukebailey** [comment]
Details sent over, it looks like the Vimeo API does not return the file exention in the REST request for a thumbnail which would explain the issue. 

![image](https://user-images.githubusercontent.com/3185073/117958097-9a090e00-b312-11eb-8aa1-30245d38c52a.png)

Unsure when or why this changed (https://developer.vimeo.com/api/changelog) but assume this now needs to be handled in the plugin explicitly.

**Comment by jeffBenusa** [comment]
This won't be the fix but I got my sites back up by adding a condition if there was a .jpg file extension.  All my other thumbnails saved were in .jpg

`vendor/dukt/videos/src/services/Videos.php:110`

`if ($response) {
    $needle = '.jpg';
    $length = strlen($needle);
    if (substr($response->thumbnailSource, -$length) !== $needle) {
      $response->thumbnailSource .= $needle;
    }

    return $response;
}`

**Comment by stevehurst** [comment]
I'm having this same issue on Craft CMS 3.5.15.1. I tried jeffBenusa's hot fix, but did not fix our Internal Server Errors on entries with Video fields.

**Comment by stevehurst** [comment]
The Internal Server Error is only happening on our production server, not in our local dev environments.

**Comment by lukebailey** [comment]
Hi @benjamindavid is there any update on a fix for this issue?

**Comment by benjamindavid** [comment]
So the error was due to the fact that sometimes Vimeo provides thumbnails without a file extension. It's not a problem if you're using Imagick, but GD didn't like it.

The issue has been fixed in [Videos 2.0.15](https://github.com/dukt/videos/blob/master/CHANGELOG.md#2015---2021-05-19). Thanks for your feedback!
