### ISSUE TITLE
Fields losing their value when updating search index

### ISSUE THREAD

**Issue by luke-nehemedia** [dukt/videos#55]
### Description
I had to fix an issue at a client's page by rebuilding the search index by using `./craft resave/entries --section=xxx site=xxx --update-search-index`. My issue was fixed, however, all video fields lost their value and where empty thereafter.

There were filled with Vimeo videos. I therefore do not know whether the same problem exists with YouTube videos.

### Steps to reproduce
1. Run `--update-search-index` on a site
2. See how all video fields are empty thereafter ;-)

### Additional info
- Plugin version: 2.0.15
- Craft version: Craft Pro 3.6.17
- PHP version: 7.3.28
- Database driver & version: MySQL 5.7.22
- Plugins & versions:

**Comment by luke-nehemedia** [comment]
Any information when an update is likely to appear?
It keeps me from fixing some search-related issues on the clients site.

**Comment by benjamindavid** [comment]
Sorry about that, I've just managed to replicate that one and it seems to happen when resaving entries, but with the Vimeo/YouTube account disconnected. We'll try to find a way to prevent it from resaving the video field if the API can't be reached, but in the meaning, just make sure that you are properly connected to your account should do the trick.

**Comment by luke-nehemedia** [comment]
Thank you for your answer. Unfortunately, I cannot confirm this. On both sites the Vimeo-account (YouTube is not used) is connected properly. There are also no problems with changing videos, loading the list of uploaded videos etc.

**Comment by benjamindavid** [comment]
Weird… Have you tried to disconnect and reconnect the Vimeo account?

**Comment by luke-nehemedia** [comment]
I will give this a try the following days. Have to make some arrangements to be able to rollback everything quickly.

**Comment by luke-nehemedia** [comment]
Seems to work now. I am not sure whether you have fixed something or it is related to a craft update or anything else. 
Whatever the reason: It works now :)
