### ISSUE TITLE
Unable to upgrade to Craft 3.7

### ISSUE THREAD

**Issue by baileydoestech** [dukt/videos#56]
### Description
Seems like the same issue reported here: https://github.com/dukt/videos/issues/49 when upgrading to Craft 3.6

![image](https://user-images.githubusercontent.com/3185073/126658031-5f2839a9-cc34-498c-b7ee-a099c3907093.png)

### Steps to reproduce

1. Upgrade to Craft 3.7
2. 500 erorr on any Craft admin pages using video field

### Additional info

- Plugin version: latest
- Craft version: 3.7.4
- PHP version: 8.0
- Database driver & version: mysql

**Comment by lukebailey** [comment]
This seems to disappear when revisting the page after a minute or so, almost as if the thumbnail generation is timingout the first time but then completing shortly after.
