### ISSUE TITLE
Vimeo Connection Issues / Bugs

### ISSUE THREAD

**Issue by hybridinteractive** [dukt/videos#6]
Not sure what's happening here but I setup a Vimeo app on `/admin/videos/settings` and getting this even after successfully getting the Vimeo "Allow Access":

![screen shot 2018-03-27 at 2 10 51 pm](https://user-images.githubusercontent.com/5711553/37992377-cc514b9e-31c8-11e8-92ff-918b2ad48f3a.png)

Then on `/admin/videos/settings/vimeo` I'm seeing this:

![screen shot 2018-03-27 at 2 12 07 pm](https://user-images.githubusercontent.com/5711553/37992412-e95fae10-31c8-11e8-9e7b-4c1e4a577c1e.png)

Any thoughts?

**Comment by steve71p** [comment]
Hi, I 'm having the same issue... and its driving me mad. Did you fine a solution?

**Comment by benjamindavid** [comment]
Sorry guys, it was an issue with the Vimeo OAuth provider:
https://github.com/dukt/oauth2-vimeo/commit/fedd7534397728e87899a6639f6cc1dedf35168f

I've just pushed a new Videos 2.0.0-beta.7 release which should fix this issue:
https://github.com/dukt/videos/releases/tag/2.0.0-beta.7
