### ISSUE TITLE
When running php craft project-config/apply we keep getting a schemaVersion conflict

### ISSUE THREAD

**Issue by a-am** [dukt/videos#65]
When running `php craft project-config/apply` we keep getting a schemaVersion conflict. 
ERROR: `Videos is installed with schema version of 1.0.3 while 1.0.4 was expected.`
I have checked the Database plugins table, the composer.lock file and the project.yaml file and all of them say schema version 1.0.4.  However in the Plugin.php file on[ line 44](https://github.com/dukt/videos/blob/a5204095e37a015fc76a09f3d9e6ca9d7a4a6056/src/Plugin.php#L44) it says schemaVersion set to 1.0.3.

### Steps to reproduce

1. Update videos plugin
2. Try to run in console `php craft project-config/apply`

### Additional info

- Plugin version: 2.1.0
- Craft version: 3.7.37
- PHP version: 8.0.17
- Database driver & version: MySQL 8.0.27

**Comment by a-am** [comment]
@benjamindavid we installed the plugin about a year ago from the plugin store. Not sure how or why this is occurring.  We have had this happen on multiple sites.

**Comment by benjamindavid** [comment]
Well, that's weird, `1.0.4` never existed, maybe some search/replace gone wrong or something? Which version of the plugin did you upgrade from?

Also, does changing 1.0.4 → 1.0.3 fix the issue?

**Comment by a-am** [comment]
Yes changing 1.0.4 to 1.0.3 does fix it.  If this is not an issue I will just update those values and hopefully going forward it won't be an issue.
