### ISSUE TITLE
[v3.x] Bug - Unhandled error when Videos can't resolve thumbnail MIME type (Vimeo)

### ISSUE THREAD

**Issue by tomdavies** [dukt/videos#71]
### Description

The plugin throws an unhandled error when unable to determine the MIME type of a video thumbnail image. We hit this issue specifically with Vimeo thumbs, across all the videos that we tried (5+). I think this is happening specifically for Vimeo thumbnail images because they are served without file extensions...

**EDIT: I've figured out this only happens when also passing a width to `getThumbnail()`, as otherwise we just use the Vimeo thumbnail URL rather than grabbing the image and transforming it:**

```twig
{# this will work #}
{{ video.getThumbnail() }}
{# this will error #}
{{ video.getThumbnail(300) }}
```
Original issue:

In [`VideosHelper::getVideoThumbnail():#L138-L149`](https://github.com/dukt/videos/blob/562e101b99d118649fbd9b1d6252e76cf8d840c6/src/helpers/VideosHelper.php#L131-L146) we have

```php
  $mimeByExt = FileHelper::getMimeTypeByExtension($originalPath);
  
  if (!$mimeByExt) {
      // Add the extension to the filename if it doesn’t have one
      $mime = FileHelper::getMimeType($originalPath); //<---- this can be an unhandled null
      $ext = FileHelper::getExtensionByMimeType($mime);


      if ($ext !== '' && $ext !== '0') {
          ....
      }
  }
```
However as of Craft 4, [`FileHelper::getMimeType()`](https://github.com/craftcms/cms/blob/55776d666f8a99a316af55f00365b8ba46c7ae60/src/helpers/FileHelper.php#L266-L281) can return a `null`, which the current plugin code does not handle.

Adding a check + early return for this allows the error to be handled gracefully, albeit without showing the image.

```php
    // Add the extension to the filename if it doesn’t have one
    $mime = FileHelper::getMimeType($originalPath);

    if (!$mime) {
        return null;
    }
```

### Steps to reproduce

1. Create a video field, connect to Vimeo and add a Vimeo video URL
2. Attempt to call `videoField.getThumbnail()` from template

Stack trace:

<img width="1070" alt="Screenshot 2022-10-17 at 14 45 01" src="https://user-images.githubusercontent.com/136308/196193509-5ded69d7-e6b8-4f2d-9352-ca994d024119.png">

### Additional info

- Plugin version: 3.0.0-beta.1
- Craft version: 4.2.7
- PHP version: 8.1.11
- Database driver & version: MySQL 10.3.36
- [Example Vimeo URL](https://vimeo.com/1386943)

**Comment by benjamindavid** [comment]
Fixed by #73
