### ISSUE TITLE
Are Dukt plugins abandoned?

### ISSUE THREAD

**Issue by jamesmacwhite** [dukt/videos#81]
### Description

Hi. I'm writing this issue as the organisation I work for that uses these plugins has paid licences for both the Dukt Twitter and Videos plugins (recently renewed), however I'm a little concerned on the lack of updates/addressing of bugs identified for a while.

There are several pull requests which fix issues identified but have been unmerged for a while:

* https://github.com/dukt/videos/pull/78
* https://github.com/dukt/videos/pull/73
* https://github.com/dukt/videos/pull/58

The Craft CMS 4 version of this plugin is also labelled as BETA and never formally had a stable release and also hasn't been updated for over a year either.

As these are paid plugins, I think it is fair to expect some level of support and maintenance in regards to these issues.

I fully appreicate developers of plugins may have many other commitments and things in life happen, but as there are likely many others also paying for licences, I think there should be a reasonable expectation of some commitment to maintaining these plugins.

I would prefer not to fork the Dukt plugins, but this is what it may come to, or look for an alternative solution entirely, which may be at further expense/development time for our organisation.

I don't usually like doing issue posts like this, but if no response is received regarding the status of these plugins, I will refer it to support@craftcms.com, as I would have to highlight these plugins being paid/commericial are not fullfilling the support/on-going maintenance expectations for those who are paying for licences for them.

I hope to hear an update on the status of these plugins soon, which I'm sure others will to.

Thank you.

**Comment by benjamindavid** [comment]
First I want to say I’m sorry for the lack of updates on this, things definitely got crazy on my end and the plugins didn’t get they attention they needed. So in an effort to improve the work and focus on those plugins, Facebook and Twitter plugins have been abandoned and Social is becoming free. Videos will get a release by the end of the week which will finally take it out of beta and contain the fixes and PRs listed here. Most of the Analytics plugin has been rewritten and it’s about to be ready to make its big transition from Universal Analytics to GA4 in a release that will take it out of beta as well, a bit after Videos. Again I’m sorry about this whole situation and the lack of updates but I’m confident about these new adjustments that will hopefully better align with what everyone rightfully expects.

**Comment by jamesmacwhite** [comment]
Hi @benjamindavid Thank you for the update. Fully appreicate other things can get in the way, it was just to understand what the situation is with some of the plugins, given the lack of updates or communication.

Given Twitter's recent API pricing changes, it is unlikely most will be able to use the Twitter plugin anyway as reading tweets now costs $5,000 USD a month through the API as it's now in the Pro tier! No thanks!
